### ISSUE TITLE
Hot Key for Plugin translation activation

### ISSUE THREAD

**Issue by vekamesh** [awslabs/amazon-translate-browser-extension#27]
Will be implementing a way to just click a hot key (ex. F6) which will automatically translate the whole page or selected area(another issue to be created). 

Also adding the ability to modify/change the hot key the user would like to use in the plugin settings page.

**Comment by AJStacy** [comment]
I would steer clear of function keys because their functionality can vary based on OS. I would suggest doing cmd + alt + t (or ctrl + alt + t for non-mac systems).
